---
- name: Add SSH user
  user:
    name: "{{ ssh_user_name }}"
    state: present
  become: yes

- name: Add SSH user to SSH group
  user:
    name: "{{ ssh_user_name }}"
    group: "{{ ssh_allowed_group }}"
    state: present
  become: yes

- name: Create a .ssh direcotry for the SSH user
  file:
    path: "/home/{{ ssh_user_name }}/.ssh"
    state: directory
    mode: "0700"
  become_user: "{{ ssh_user_name }}"

- name: Create authorized_keys file
  copy:
    content: "{{ ssh_public_keys | join('\n') }}"
    dest: "/home/{{ ssh_user_name }}/.ssh/authorized_keys"
    mode: "0600"
  become_user: "{{ ssh_user_name }}"
