---
- name: Copy templates/
  ansible.builtin.template:
    src: "templates/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
  become: yes

- name: Copy files/
  ansible.builtin.copy:
    src: "files/sshd"
    dest: "/etc/pam.d/sshd"
  become: yes
  notify: Restart SSH
