---
#- name: Wating for dpkg lock to be released
#  wait_for:
#    path: /var/lib/dpkg/lock
#    state: absent
#    timeout: 10

- name: Ensure presence of Google Authenticator on remote machine
  apt:
    name: libpam-google-authenticator
    state: present
